
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadCsv(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_csv", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGraphData() : Promise<Result<GraphData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_graph_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getShortestPath(start: string, end: string) : Promise<Result<PathResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_shortest_path", { start, end }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNearby(person: string, radius: number) : Promise<Result<NearbyPerson[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_nearby", { person, radius }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReachable(person: string, hops: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_reachable", { person, hops }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyze() : Promise<Result<AnalysisResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCircle(person: string) : Promise<Result<CircleMember[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_circle", { person }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInfo(person: string) : Promise<Result<PersonInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_info", { person }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AnalysisResult = { core: PersonStats[]; active: PersonStats[]; edge: PersonStats[] }
export type CircleMember = { name: string; weight: number }
export type Coordinate = { x: number; y: number }
export type Edge = { source: string; target: string; weight: number }
export type GraphData = { nodes: Node[]; edges: Edge[] }
export type NearbyPerson = { name: string; distance: number }
export type Node = { name: string; loc: Coordinate }
export type PathResult = { path: string[]; hops: number }
export type PersonInfo = { name: string; index: number; loc: Coordinate; connections: number }
export type PersonStats = { name: string; degree: number; weight_sum: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
